name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /saymecgo.infinityfree.com/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            database.sql
            README.md